# Generated by Django 5.1.1 on 2025-01-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_book_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.CharField(blank=True),
        ),
    ]
