# Generated by Django 5.1.1 on 2025-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', unique=True),
        ),
    ]
